pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
permalink: articles/:categories/:title:output_ext
gems:
  - jekyll-paginate-v2
url: "https://consulting.0x4447.com"
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-environment-variables  
  - jekyll-sitemap
  - jekyll-seo-tag
name: AWS Cloud Consulting
description: "Drive business growth with personalized AWS consulting through 0x4447 to implement cost-effective customer solutions built on scalable cloud infrastructure."
author: David Gatti
after-name: "0x4447"
generator: Jekyll v4.1.1
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - assets/libs/flickity-fade/sandbox/
  #- assets/libs/typed.js/index.html