pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title_suffix: ' - :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
permalink: /articles/:categories/:title:output_ext
gems:
  - jekyll-paginate-v2
url: "https://consulting.0x4447.com"
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  