version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler
  pre_build:
    commands:
      - DISTRIBUTION_ID=$DISTRIBUTION_ID
      - S3_BUCKET_WEBPAGE=$S3_BUCKET_WEBPAGE

      - echo AWS_REGION=$AWS_REGION >> .env

      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - aws s3 rm --recursive s3://$S3_BUCKET_WEBPAGE
      - aws s3 cp ./_site s3://$S3_BUCKET_WEBPAGE --recursive
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"